version: 2.1

executors:
  ios-executor:
    macos:
      xcode: "15.3.0" # Select the appropriate Xcode version

jobs:
  build-and-test:
    executor: ios-executor
    steps:
      - checkout # Check out the code from the repository

      # Resolve Swift Package Manager dependencies (This will happen automatically with the build)
      - run:
          name: Resolve SPM Dependencies
          command: |
            xcodebuild -resolvePackageDependencies \
              -project SwiftUI_Playground.xcodeproj \
              -scheme SwiftUI_Playground

      # Set up keychain (for code signing if necessary)
      - run:
          name: Create Keychain
          command: |
            security create-keychain -p "" circle.keychain
            security default-keychain -s circle.keychain
            security unlock-keychain -p "" circle.keychain

      # Build the app
      - run:
          name: Build the project
          command: |
            xcodebuild clean build \
              -project SwiftUI_Playground.xcodeproj \
              -scheme SwiftUI_Playground \
              -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.0' \
              CODE_SIGNING_ALLOWED=NO

      # Run tests
      - run:
          name: Run Unit Tests
          command: |
            xcodebuild test \
              -project SwiftUI_Playground.xcodeproj \
              -scheme SwiftUI_Playground \
              -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.0'

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test

