version: 2.1

jobs:
  build_and_test:
    macos:
      xcode: 15.3.0 # Specify the Xcode version

    steps:
      - checkout
      
      # Restore SPM Cache
      - restore_cache:
          keys:
            - spm-dependency-cache-{{ checksum "Package.resolved" }}
            - bundle-cache-{{ checksum "Gemfile.lock" }}
            - homebrew-cache-v1

      - run:
          name: Setup GoogleService-Info.plist
          working_directory: SwiftUI_Playground/Resources/Firebase
          command: |
            echo "${GOOGLE_SERVICE_INFO_PLIST_BASE64}" | base64 -d > GoogleService-Info.plist
            if [ $? -eq 0 ]; then
              echo "GoogleService-Info.plist decoded successfully"
            else
              echo "Failed to decode GoogleService-Info.plist" >&2
              exit 1
            fi

      - run:
          name: Resolve Swift Packages
          command: xcodebuild -resolvePackageDependencies -scheme "SwiftUI_Playground"

      # Save SPM Cache
      - save_cache:
          key: spm-dependency-cache-{{ checksum "Package.resolved" }}
          paths:
            - ~/Library/Developer/Xcode/DerivedData
            - ~/Library/Caches/org.swift.swiftpm
            - ~/Library/Caches/com.apple.dt.Xcode/Downloads

      # Install and Cache Bundler Dependencies
      - run:
          name: Install Bundler Dependencies
          command: bundle install --path vendor/bundle

      - save_cache:
          key: bundle-cache-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: Debug Environment Variables
          command: |
            echo "CI: $CI"
            echo "CIRCLECI: $CIRCLECI"
            echo "CIRCLE_PULL_REQUEST: $CIRCLE_PULL_REQUEST"
            echo "CIRCLE_PROJECT_USERNAME: $CIRCLE_PROJECT_USERNAME"
            echo "CIRCLE_PROJECT_REPONAME: $CIRCLE_PROJECT_REPONAME"

      # Install and Cache SwiftLint
      - run:
          name: Install SwiftLint
          command: brew install swiftlint

      - save_cache:
          key: homebrew-cache-v1
          paths:
            - /usr/local/Homebrew

      - run:
          name: Run Danger
          command: bundle exec danger

      - run:
          name: Run Fastlane Tests
          command: bundle exec fastlane test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_and_test:
          filters:
            tags:
              ignore: /.*/ # Ignore tags
