version: 2.1

jobs:
  build_and_test:
    macos:
      xcode: 15.3.0 # Specify the Xcode version
    environment:
      GOOGLE_PLIST_CONTENT: ${GOOGLE_PLIST_CONTENT} # Make sure this is set in CircleCI Project Settings
    steps:
      - checkout
      - run:
          name: Set up GoogleService-Info.plist
          command: |
            if [ -z "$GOOGLE_PLIST_CONTENT" ]; then
              echo "❌ GOOGLE_PLIST_CONTENT is not set."
              exit 1
            fi
            echo "$GOOGLE_PLIST_CONTENT" | base64 --decode > SwiftUI_Playground/Resources/Firebase/GoogleService-Info.plist
            echo "✅ GoogleService-Info.plist has been set."

      - run:
          name: Install Dependencies
          command: bundle install
      - run:
          name: Debug Environment Variables
          command: |
            echo "CI: $CI"
            echo "CIRCLECI: $CIRCLECI"
            echo "CIRCLE_PULL_REQUEST: $CIRCLE_PULL_REQUEST"
            echo "CIRCLE_PROJECT_USERNAME: $CIRCLE_PROJECT_USERNAME"
            echo "CIRCLE_PROJECT_REPONAME: $CIRCLE_PROJECT_REPONAME"
      - run:
          name: Install SwiftLint
          command: brew install swiftlint
      - run:
          name: Install IBliner
          command: brew install iblinter
      - run:
          name: Run Danger
          command: bundle exec danger
      - run:
          name: Run Fastlane
          command: bundle exec fastlane test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_and_test:
          filters:
            tags:
              ignore: /.*/ # Ignore tags
